#lang racket

(define (memq item x)
  (cond ((null? x) false)
        ((eq? item (car x)) x)
        (else (memq item (cdr x)))))

(memq 'apple '(pear banana prune))
(newline)
(memq 'apple '(x (apple sauce) y apple pear))
(newline)
(list 'a 'b 'c)
(newline)
(list (list 'george))
(newline)
(cdr '((x1 x2) (y1 y2)))
(newline)
(cadr '((x1 x2) (y1 y2)))
(newline)
(pair? (car '(a short list)))
(newline)
(memq 'red '((red shoes) (blue socks)))
(newline)
(memq 'red '(red shoes blue socks))
(newline)
